### ISSUE TITLE
单元测试

### ISSUE THREAD

**Issue by a406299736** [fantastic-admin/basic#43]
在项目里使用单元测试时，报错：
Failed to resolve entry for package "@webassemblyjs/helper-api-error". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1225:21:
      1225 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///xxx/node_modules/.pnpm/vite@5.3.2_@types+node@20.14.9_sass@1.77.6_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:47164:15)
    at resolvePackageEntry (file:///xxx/node_modules/.pnpm/vite@5.3.2_@types+node@20.14.9_sass@1.77.6_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:47161:3)

**Comment by hooray** [comment]
请提供下完整的复现步骤
